<a href="https://colab.research.google.com/github/Samujjalborah/python-learning-journey/blob/main/Day_8_E_commerce_Sales_Analysis_using_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Day 8 - E-commerce Sales Analysis using Pandas

## Objective

This notebook analyzes an e-commerce sales dataset using the Pandas library. The analysis includes data selection, filtering, sorting, grouping, aggregation, and statistical summaries to understand sales performance across different categories, cities, products, and payment methods.

**Developed by:** Samujjal Borah

In [2]:
import pandas as pd
df=pd.read_csv('ecommerce_sales.csv')
df

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
0,1001,2026-02-27,Kabir Ali,Hyderabad,South,Electronics,Wireless Headphones,3,1499,0,4497.00,3.8,Cash on Delivery
1,1002,2026-01-24,Aditya Verma,Jammu,North,Sports,Running Shoes,1,2799,0,2799.00,4.1,Cash on Delivery
2,1003,2026-04-18,Sara Ahmed,Chennai,South,Electronics,Power Bank,2,1199,15,2038.30,4.6,Cash on Delivery
3,1004,2026-03-13,Kabir Ali,Lucknow,North,Electronics,Mechanical Keyboard,4,2499,5,9496.20,4.1,Debit Card
4,1005,2026-03-30,Priya Menon,Jammu,North,Electronics,Smart Watch,1,3299,5,3134.05,4.2,UPI
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1096,2026-01-26,Aditya Verma,Kochi,South,Sports,Dumbbell Set,5,1999,5,9495.25,4.2,Credit Card
96,1097,2026-02-02,Arjun Nair,Mumbai,West,Clothing,T-Shirt,1,799,15,679.15,3.5,UPI
97,1098,2026-01-04,Yusuf Dar,Bengaluru,South,Home & Kitchen,Electric Kettle,4,1499,0,5996.00,4.2,Net Banking
98,1099,2026-03-06,Hiba Sheikh,Ahmedabad,West,Books,Machine Learning Basics,2,999,0,1998.00,3.8,UPI
99,1100,2026-02-08,Kabir Ali,Pune,West,Books,Data Science Handbook,5,899,0,4495.00,4.8,Debit Card

## Display First Five Rows

In [3]:
df.head()

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
0,1001,2026-02-27,Kabir Ali,Hyderabad,South,Electronics,Wireless Headphones,3,1499,0,4497.00,3.8,Cash on Delivery
1,1002,2026-01-24,Aditya Verma,Jammu,North,Sports,Running Shoes,1,2799,0,2799.00,4.1,Cash on Delivery
2,1003,2026-04-18,Sara Ahmed,Chennai,South,Electronics,Power Bank,2,1199,15,2038.30,4.6,Cash on Delivery
3,1004,2026-03-13,Kabir Ali,Lucknow,North,Electronics,Mechanical Keyboard,4,2499,5,9496.20,4.1,Debit Card
4,1005,2026-03-30,Priya Menon,Jammu,North,Electronics,Smart Watch,1,3299,5,3134.05,4.2,UPI

## Display Last Five Rows

In [5]:
df.tail()

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
95,1096,2026-01-26,Aditya Verma,Kochi,South,Sports,Dumbbell Set,5,1999,5,9495.25,4.2,Credit Card
96,1097,2026-02-02,Arjun Nair,Mumbai,West,Clothing,T-Shirt,1,799,15,679.15,3.5,UPI
97,1098,2026-01-04,Yusuf Dar,Bengaluru,South,Home & Kitchen,Electric Kettle,4,1499,0,5996.00,4.2,Net Banking
98,1099,2026-03-06,Hiba Sheikh,Ahmedabad,West,Books,Machine Learning Basics,2,999,0,1998.00,3.8,UPI
99,1100,2026-02-08,Kabir Ali,Pune,West,Books,Data Science Handbook,5,899,0,4495.00,4.8,Debit Card

## Dataset Information

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          100 non-null    int64
 1   Order_Date        100 non-null    object
 2   Customer          100 non-null    object
 3   City              100 non-null    object
 4   Region            100 non-null    object
 5   Category          100 non-null    object
 6   Product           100 non-null    object
 7   Quantity          100 non-null    int64
 8   Unit_Price        100 non-null    int64
 9   Discount_Percent  100 non-null    int64
 10  Total_Sales       100 non-null    float64
 11  Rating            100 non-null    float64
 12  Payment_Method    100 non-null    object
dtypes: float64(2), int64(4), object(7)
memory usage: 10.3+ KB

## Dataset Shape

In [7]:
print(df.shape)

(100, 13)

## Column Names

In [8]:
df.columns

Index(['Order_ID', 'Order_Date', 'Customer', 'City', 'Region', 'Category',
       'Product', 'Quantity', 'Unit_Price', 'Discount_Percent', 'Total_Sales',
       'Rating', 'Payment_Method'],
      dtype='object')

## Select Required Columns

In [9]:
df[["Customer","City","Category","Product","Total_Sales"]].head()

       Customer       City     Category              Product  Total_Sales
0     Kabir Ali  Hyderabad  Electronics  Wireless Headphones      4497.00
1  Aditya Verma      Jammu       Sports        Running Shoes      2799.00
2    Sara Ahmed    Chennai  Electronics           Power Bank      2038.30
3     Kabir Ali    Lucknow  Electronics  Mechanical Keyboard      9496.20
4   Priya Menon      Jammu  Electronics          Smart Watch      3134.05

## Select Required Columns

In [10]:
df[["Customer","City","Category","Product","Total_Sales"]].head()

       Customer       City     Category              Product  Total_Sales
0     Kabir Ali  Hyderabad  Electronics  Wireless Headphones      4497.00
1  Aditya Verma      Jammu       Sports        Running Shoes      2799.00
2    Sara Ahmed    Chennai  Electronics           Power Bank      2038.30
3     Kabir Ali    Lucknow  Electronics  Mechanical Keyboard      9496.20
4   Priya Menon      Jammu  Electronics          Smart Watch      3134.05

## Filter Orders Above ₹5000

In [11]:
df[df["Total_Sales"]>5000]

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
3,1004,2026-03-13,Kabir Ali,Lucknow,North,Electronics,Mechanical Keyboard,4,2499,5,9496.20,4.1,Debit Card
7,1008,2026-04-27,Aman Kumar,Jammu,North,Clothing,Hoodie,4,1599,5,6076.20,4.3,Credit Card
9,1010,2026-03-11,Aman Kumar,Kochi,South,Clothing,Jacket,4,2499,10,8996.40,4.7,Credit Card
10,1011,2026-03-22,Rahul Das,Hyderabad,South,Home & Kitchen,Coffee Maker,2,3499,0,6998.00,4.2,UPI
12,1013,2026-03-09,Maryam Khan,Lucknow,North,Clothing,Jacket,5,2499,15,10620.75,4.8,Net Banking
13,1014,2026-02-05,Dev Patel,Jaipur,North,Sports,Running Shoes,3,2799,0,8397.00,4.6,UPI
16,1017,2026-03-17,Sana Malik,Hyderabad,South,Sports,Cricket Bat,3,2499,0,7497.00,4.0,Net Banking
18,1019,2026-05-19,Reyansh Jain,Chennai,South,Clothing,Jacket,3,2499,0,7497.00,4.7,UPI
27,1028,2026-04-19,Sana Malik,Chandigarh,North,Electronics,Wireless Headphones,4,1499,5,5696.20,4.6,UPI
28,1029,2026-01-28,Sara Ahmed,Hyderabad,South,Electronics,Wireless Headphones,4,1499,5,5696.20,4.1,Credit Card
32,1033,2026-06-28,Maryam Khan,Pune,West,Home & Kitchen,Mixer Grinder,3,2999,10,8097.30,4.7,Net Banking
37,1038,2026-03-08,Aditya Verma,Pune,West,Sports,Dumbbell Set,5,1999,5,9495.25,5.0,Debit Card
38,1039,2026-04-28,Vivaan Kapoor,Chandigarh,North,Home & Kitchen,Mixer Grinder,2,2999,5,5698.10,3.8,UPI
40,1041,2026-03-14,Ishita Gupta,Delhi,North,Home & Kitchen,Coffee Maker,2,3499,5,6648.10,4.6,Cash on Delivery
47,1048,2026-06-24,Sara Ahmed,Lucknow,North,Home & Kitchen,Coffee Maker,3,3499,0,10497.00,5.0,UPI
48,1049,2026-03-02,Ishita Gupta,Mumbai,West,Sports,Running Shoes,5,2799,0,13995.00,4.0,Net Banking
50,1051,2026-04-28,Aisha Mir,Bhubaneswar,East,Electronics,Smart Watch,2,3299,0,6598.00,4.2,Credit Card
51,1052,2026-03-13,Rohan Mehta,Chandigarh,North,Electronics,Mechanical Keyboard,4,2499,5,9496.20,4.2,Debit Card
52,1053,2026-01-08,Ananya Singh,Hyderabad,South,Sports,Running Shoes,5,2799,5,13295.25,4.2,Credit Card
56,1057,2026-03-21,Alina Shah,Chennai,South,Home & Kitchen,Coffee Maker,3,3499,15,8922.45,4.5,Debit Card
58,1059,2026-01-01,Mehak Bhat,Chennai,South,Sports,Cricket Bat,4,2499,15,8496.60,4.2,Credit Card
59,1060,2026-04-24,Karan Joshi,Pune,West,Sports,Dumbbell Set,3,1999,10,5397.30,5.0,Credit Card
61,1062,2026-02-20,Kabir Ali,Mumbai,West,Electronics,Mechanical Keyboard,3,2499,0,7497.00,3.5,UPI
65,1066,2026-06-20,Dev Patel,Jaipur,North,Electronics,Smart Watch,2,3299,10,5938.20,4.7,Cash on Delivery
69,1070,2026-06-30,Aditya Verma,Delhi,North,Clothing,Jacket,4,2499,0,9996.00,3.8,Net Banking
75,1076,2026-04-29,Ishita Gupta,Chennai,South,Electronics,Wireless Headphones,4,1499,0,5996.00,3.5,Debit Card
76,1077,2026-03-28,Reyansh Jain,Pune,West,Home & Kitchen,Electric Kettle,4,1499,5,5696.20,4.5,Debit Card
79,1080,2026-05-25,Aditya Verma,Delhi,North,Clothing,Jacket,4,2499,0,9996.00,4.6,Debit Card
80,1081,2026-01-30,Reyansh Jain,Kolkata,East,Home & Kitchen,Electric Kettle,5,1499,15,6370.75,4.0,Debit Card
84,1085,2026-01-28,Sana Malik,Hyderabad,South,Home & Kitchen,Coffee Maker,4,3499,10,12596.40,4.3,Net Banking
89,1090,2026-05-13,Aditya Verma,Lucknow,North,Sports,Cricket Bat,5,2499,0,12495.00,3.8,Credit Card
92,1093,2026-05-16,Aisha Mir,Hyderabad,South,Sports,Cricket Bat,4,2499,15,8496.60,4.5,Cash on Delivery
93,1094,2026-03-06,Sara Ahmed,Mumbai,West,Home & Kitchen,Mixer Grinder,3,2999,5,8547.15,3.8,Credit Card
95,1096,2026-01-26,Aditya Verma,Kochi,South,Sports,Dumbbell Set,5,1999,5,9495.25,4.2,Credit Card
97,1098,2026-01-04,Yusuf Dar,Bengaluru,South,Home & Kitchen,Electric Kettle,4,1499,0,5996.00,4.2,Net Banking

## Filter Electronics Category

In [12]:
df[df["Category"]=="Electronics"]

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
0,1001,2026-02-27,Kabir Ali,Hyderabad,South,Electronics,Wireless Headphones,3,1499,0,4497.00,3.8,Cash on Delivery
2,1003,2026-04-18,Sara Ahmed,Chennai,South,Electronics,Power Bank,2,1199,15,2038.30,4.6,Cash on Delivery
3,1004,2026-03-13,Kabir Ali,Lucknow,North,Electronics,Mechanical Keyboard,4,2499,5,9496.20,4.1,Debit Card
4,1005,2026-03-30,Priya Menon,Jammu,North,Electronics,Smart Watch,1,3299,5,3134.05,4.2,UPI
14,1015,2026-06-24,Sana Malik,Kolkata,East,Electronics,Wireless Headphones,2,1499,0,2998.00,4.8,UPI
25,1026,2026-05-12,Sara Ahmed,Chandigarh,North,Electronics,Wireless Headphones,3,1499,0,4497.00,4.2,Net Banking
27,1028,2026-04-19,Sana Malik,Chandigarh,North,Electronics,Wireless Headphones,4,1499,5,5696.20,4.6,UPI
28,1029,2026-01-28,Sara Ahmed,Hyderabad,South,Electronics,Wireless Headphones,4,1499,5,5696.20,4.1,Credit Card
36,1037,2026-06-02,Zoya Khan,Pune,West,Electronics,Power Bank,2,1199,15,2038.30,4.8,UPI
46,1047,2026-02-07,Sana Malik,Bengaluru,South,Electronics,Wireless Mouse,5,899,15,3820.75,4.0,UPI
50,1051,2026-04-28,Aisha Mir,Bhubaneswar,East,Electronics,Smart Watch,2,3299,0,6598.00,4.2,Credit Card
51,1052,2026-03-13,Rohan Mehta,Chandigarh,North,Electronics,Mechanical Keyboard,4,2499,5,9496.20,4.2,Debit Card
61,1062,2026-02-20,Kabir Ali,Mumbai,West,Electronics,Mechanical Keyboard,3,2499,0,7497.00,3.5,UPI
65,1066,2026-06-20,Dev Patel,Jaipur,North,Electronics,Smart Watch,2,3299,10,5938.20,4.7,Cash on Delivery
68,1069,2026-03-27,Vivaan Kapoor,Ahmedabad,West,Electronics,Wireless Mouse,2,899,5,1708.10,4.7,UPI
75,1076,2026-04-29,Ishita Gupta,Chennai,South,Electronics,Wireless Headphones,4,1499,0,5996.00,3.5,Debit Card
83,1084,2026-06-19,Aisha Mir,Kolkata,East,Electronics,Wireless Mouse,5,899,10,4045.50,3.8,Cash on Delivery
91,1092,2026-04-14,Nikhil Sood,Ahmedabad,West,Electronics,Wireless Headphones,3,1499,0,4497.00,4.1,Debit Card
94,1095,2026-02-25,Maryam Khan,Mumbai,West,Electronics,Power Bank,2,1199,0,2398.00,4.6,Debit Card

## Sort by Highest Sales

In [13]:
df.sort_values(by="Total_Sales",ascending=False).head(10)

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
48,1049,2026-03-02,Ishita Gupta,Mumbai,West,Sports,Running Shoes,5,2799,0,13995.00,4.0,Net Banking
52,1053,2026-01-08,Ananya Singh,Hyderabad,South,Sports,Running Shoes,5,2799,5,13295.25,4.2,Credit Card
84,1085,2026-01-28,Sana Malik,Hyderabad,South,Home & Kitchen,Coffee Maker,4,3499,10,12596.40,4.3,Net Banking
89,1090,2026-05-13,Aditya Verma,Lucknow,North,Sports,Cricket Bat,5,2499,0,12495.00,3.8,Credit Card
12,1013,2026-03-09,Maryam Khan,Lucknow,North,Clothing,Jacket,5,2499,15,10620.75,4.8,Net Banking
47,1048,2026-06-24,Sara Ahmed,Lucknow,North,Home & Kitchen,Coffee Maker,3,3499,0,10497.00,5.0,UPI
69,1070,2026-06-30,Aditya Verma,Delhi,North,Clothing,Jacket,4,2499,0,9996.00,3.8,Net Banking
79,1080,2026-05-25,Aditya Verma,Delhi,North,Clothing,Jacket,4,2499,0,9996.00,4.6,Debit Card
51,1052,2026-03-13,Rohan Mehta,Chandigarh,North,Electronics,Mechanical Keyboard,4,2499,5,9496.20,4.2,Debit Card
3,1004,2026-03-13,Kabir Ali,Lucknow,North,Electronics,Mechanical Keyboard,4,2499,5,9496.20,4.1,Debit Card

## Sort by Rating

In [14]:
df.sort_values(by="Rating",ascending=False).head(10)

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
24,1025,2026-01-02,Rohan Mehta,Chennai,South,Sports,Football,5,799,0,3995.00,5.0,UPI
35,1036,2026-06-02,Rohan Mehta,Srinagar,North,Sports,Yoga Mat,2,899,0,1798.00,5.0,Credit Card
47,1048,2026-06-24,Sara Ahmed,Lucknow,North,Home & Kitchen,Coffee Maker,3,3499,0,10497.00,5.0,UPI
37,1038,2026-03-08,Aditya Verma,Pune,West,Sports,Dumbbell Set,5,1999,5,9495.25,5.0,Debit Card
55,1056,2026-04-21,Rohan Mehta,Srinagar,North,Sports,Dumbbell Set,2,1999,5,3798.10,5.0,Debit Card
90,1091,2026-06-26,Hiba Sheikh,Kochi,South,Books,Atomic Habits,5,599,0,2995.00,5.0,Net Banking
73,1074,2026-03-28,Alina Shah,Lucknow,North,Books,Atomic Habits,1,599,10,539.10,5.0,Net Banking
60,1061,2026-05-12,Alina Shah,Bengaluru,South,Books,Python Programming,1,749,5,711.55,5.0,Cash on Delivery
59,1060,2026-04-24,Karan Joshi,Pune,West,Sports,Dumbbell Set,3,1999,10,5397.30,5.0,Credit Card
62,1063,2026-04-17,Aman Kumar,Chandigarh,North,Books,The Alchemist,1,499,10,449.10,4.8,Credit Card

## Sales by Category

In [15]:
df.groupby("Category")["Total_Sales"].sum()

Category
Books              36792.40
Clothing           69028.20
Electronics        92086.00
Home & Kitchen    113329.90
Sports            136026.45
Name: Total_Sales, dtype: float64

## Sales by City

In [16]:
df.groupby("City")["Total_Sales"].sum()

City
Ahmedabad      14788.70
Bengaluru      13524.30
Bhubaneswar     6598.00
Chandigarh     34539.65
Chennai        47493.20
Delhi          30882.80
Hyderabad      59076.45
Jaipur         25534.00
Jammu          16059.75
Kochi          37257.50
Kolkata        20169.00
Lucknow        46194.65
Mumbai         41457.80
Pune           41908.55
Srinagar       11778.60
Name: Total_Sales, dtype: float64

## Sales by Product

In [17]:
df.groupby("Product")["Total_Sales"].sum()

Product
Atomic Habits              11590.65
Coffee Maker               51610.25
Cricket Bat                41483.40
Data Science Handbook       4495.00
Dumbbell Set               30184.90
Electric Kettle            26382.40
Football                   10307.10
Hoodie                      7675.20
Jacket                     47106.15
Jeans                       6456.60
Machine Learning Basics     5694.30
Mechanical Keyboard        26489.40
Mixer Grinder              25341.55
Power Bank                  6474.60
Python Programming          7527.45
Running Shoes              41285.25
Smart Watch                15670.25
T-Shirt                     7790.25
The Alchemist               7485.00
Water Bottle                9995.70
Wireless Headphones        33877.40
Wireless Mouse              9574.35
Yoga Mat                   12765.80
Name: Total_Sales, dtype: float64

## Sales by Payment Method

In [18]:
df.groupby("Payment_Method")["Total_Sales"].sum()

Payment_Method
Cash on Delivery     50123.30
Credit Card         106540.25
Debit Card           98064.90
Net Banking          96371.25
UPI                  96163.25
Name: Total_Sales, dtype: float64

## Total Sales

In [19]:
print(df["Total_Sales"].sum())

447262.95000000007

## Average Sales

In [20]:
print(df["Total_Sales"].mean())

4472.629500000001

## Highest Sale

In [21]:
print(df["Total_Sales"].max())

13995.0

## Lowest Sale

In [22]:
print(df["Total_Sales"].min())

449.1

## Total Quantity Sold

In [23]:
print(df["Quantity"].sum())

294

## Number of Orders

In [24]:
print(df["Order_ID"].count())

100

## Top 5 Products

In [25]:
df.groupby("Product")["Total_Sales"].sum().sort_values(ascending=False).head(5)

Product
Coffee Maker           51610.25
Jacket                 47106.15
Cricket Bat            41483.40
Running Shoes          41285.25
Wireless Headphones    33877.40
Name: Total_Sales, dtype: float64

## Top 5 Categories

In [26]:
df.groupby("Category")["Total_Sales"].sum().sort_values(ascending=False).head()

Category
Sports            136026.45
Home & Kitchen    113329.90
Electronics        92086.00
Clothing           69028.20
Books              36792.40
Name: Total_Sales, dtype: float64

## Top 5 Cities

In [27]:
df.groupby("City")["Total_Sales"].sum().sort_values(ascending=False).head()

City
Hyderabad    59076.45
Chennai      47493.20
Lucknow      46194.65
Pune         41908.55
Mumbai       41457.80
Name: Total_Sales, dtype: float64

## Payment Method Analysis

In [28]:
df.groupby("Payment_Method").agg({
    "Total_Sales":"sum",
    "Order_ID":"count"
})

                  Total_Sales  Order_ID
Payment_Method
Cash on Delivery     50123.30        15
Credit Card         106540.25        22
Debit Card           98064.90        20
Net Banking          96371.25        17
UPI                  96163.25        26

# Observations

- The dataset contains **100 orders** with sales from multiple cities and product categories.
- Electronics and Sports generate a significant share of total sales.
- A few products contribute much more revenue than others, making them top-performing products.
- UPI, Credit Card, Debit Card, Cash on Delivery, and Net Banking are all used as payment methods.
- Higher-value orders generally involve Electronics and Sports products.
- The analysis helps identify top-performing cities, categories, products, and customer purchasing patterns.

# Conclusion

Using Pandas, the e-commerce dataset was successfully analyzed through selection, filtering, sorting, grouping, and aggregation techniques. The notebook identified overall sales performance, top-selling products, leading categories, city-wise sales, payment method trends, and key business insights. These analyses can support better business decisions and future sales strategies.