<a href="https://colab.research.google.com/github/Samujjalborah/python-learning-journey/blob/main/Day_9_%E2%80%93_Processed_E_commerce_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Day 9 - Processed E-commerce Dataset using Pandas

## Objective

This notebook demonstrates how to process an e-commerce dataset by combining multiple CSV files using Pandas. The datasets are merged using `merge()`, combined using `concat()`, transformed using `apply()`, and analyzed using DateTime operations. Finally, a clean processed dataset is exported as a CSV file.

**Developed by:** Samujjal Borah

Display the datasets

In [1]:
import pandas as pd
orders = pd.read_csv("Orders.csv")
customers = pd.read_csv("Customers.csv")
products = pd.read_csv("Prodects.csv")
orders.head()
customers.head()
products.head()

  Product_ID         Product_Name     Category  Unit_Price     Brand
0       P001  Wireless Headphones  Electronics        1499  SoundMax
1       P002  Mechanical Keyboard  Electronics        2499    KeyPro
2       P003       Wireless Mouse  Electronics         899  TechGear
3       P004          Smart Watch  Electronics        3299   FitTech
4       P005           Power Bank  Electronics        1199  VoltPlus

Dataset Information

In [2]:
print("Orders")
orders.info()

print("\nCustomers")
customers.info()

print("\nProducts")
products.info()

Orders
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        120 non-null    object
 1   Order_Date      120 non-null    object
 2   Customer_ID     120 non-null    object
 3   Product_ID      120 non-null    object
 4   Quantity        120 non-null    int64
 5   Payment_Method  120 non-null    object
 6   Order_Status    120 non-null    object
dtypes: int64(1), object(6)
memory usage: 6.7+ KB

Customers
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Customer_ID      30 non-null     object
 1   Customer_Name    30 non-null     object
 2   City             30 non-null     object
 3   Region           30 non-null     object
 4   Membership_Type  30 non-null     object
dtypes: object(5)
memory usage: 1.3+ KB

Products
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product_ID    20 non-null     object
 1   Product_Name  20 non-null     object
 2   Category      20 non-null     object
 3   Unit_Price    20 non-null     int64
 4   Brand         20 non-null     object
dtypes: int64(1), object(4)
memory usage: 932.0+ bytes

Dataset Shape

In [3]:
print("Orders:", orders.shape)
print("Customers:", customers.shape)
print("Products:", products.shape)

Orders: (120, 7)
Customers: (30, 5)
Products: (20, 5)

Merge Orders + Customers

In [4]:
orders_customers = pd.merge(
    orders,
    customers,
    on="Customer_ID",
    how="inner"
)

orders_customers.head()

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New

Merge with Products

In [5]:
final_df = pd.merge(
    orders_customers,
    products,
    on="Product_ID",
    how="inner"
)

final_df.head()

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type,Product_Name,Category,Unit_Price,Brand
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium,Cricket Bat,Sports,2499,BatPro
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium,Wireless Mouse,Electronics,899,TechGear
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular,Smart Watch,Electronics,3299,FitTech
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular,Machine Learning Basics,Books,999,AIPress
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New,Coffee Maker,Home & Kitchen,3499,HomeBrew

Demonstrate concat()

In [6]:
top5 = final_df.head()
bottom5 = final_df.tail()

combined = pd.concat([top5, bottom5])

combined

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type,Product_Name,Category,Unit_Price,Brand
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium,Cricket Bat,Sports,2499,BatPro
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium,Wireless Mouse,Electronics,899,TechGear
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular,Smart Watch,Electronics,3299,FitTech
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular,Machine Learning Basics,Books,999,AIPress
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New,Coffee Maker,Home & Kitchen,3499,HomeBrew
115,O0116,2026-02-19,C025,P010,1,Net Banking,Delivered,Reyansh Jain,Kolkata,East,New,Electric Kettle,Home & Kitchen,1499,KitchenPro
116,O0117,2026-02-21,C019,P015,3,Cash on Delivery,Shipped,Yusuf Dar,Srinagar,North,New,Machine Learning Basics,Books,999,AIPress
117,O0118,2026-03-09,C025,P016,4,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New,Atomic Habits,Books,599,MindReads
118,O0119,2026-02-03,C015,P019,2,Debit Card,Delivered,Karan Joshi,Chandigarh,North,Regular,Cricket Bat,Sports,2499,BatPro
119,O0120,2026-01-21,C013,P020,1,Cash on Delivery,Cancelled,Rahul Das,Kolkata,East,Regular,Dumbbell Set,Sports,1999,StrongFit

Create Total Sales using apply()

In [7]:
final_df["Total_Sales"] = final_df.apply(
    lambda row: row["Quantity"] * row["Unit_Price"],
    axis=1
)

final_df.head()

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type,Product_Name,Category,Unit_Price,Brand,Total_Sales
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium,Cricket Bat,Sports,2499,BatPro,4998
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium,Wireless Mouse,Electronics,899,TechGear,1798
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular,Smart Watch,Electronics,3299,FitTech,3299
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular,Machine Learning Basics,Books,999,AIPress,2997
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New,Coffee Maker,Home & Kitchen,3499,HomeBrew,17495

Create Order Size using apply()

In [8]:
def order_size(quantity):

    if quantity <= 2:
        return "Small"

    elif quantity <= 4:
        return "Medium"

    else:
        return "Large"

final_df["Order_Size"] = final_df["Quantity"].apply(order_size)

final_df.head()

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type,Product_Name,Category,Unit_Price,Brand,Total_Sales,Order_Size
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium,Cricket Bat,Sports,2499,BatPro,4998,Small
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium,Wireless Mouse,Electronics,899,TechGear,1798,Small
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular,Smart Watch,Electronics,3299,FitTech,3299,Small
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular,Machine Learning Basics,Books,999,AIPress,2997,Medium
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New,Coffee Maker,Home & Kitchen,3499,HomeBrew,17495,Large

DateTime Operations

In [9]:
final_df["Order_Date"] = pd.to_datetime(final_df["Order_Date"])

Extract Month

In [10]:
final_df["Month"] = final_df["Order_Date"].dt.month_name()

Extract Day

In [11]:
final_df["Day"] = final_df["Order_Date"].dt.day

Extract Day of Week

In [12]:
final_df["Day_of_Week"] = final_df["Order_Date"].dt.day_name()

final_df.head()

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type,Product_Name,Category,Unit_Price,Brand,Total_Sales,Order_Size,Month,Day,Day_of_Week
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium,Cricket Bat,Sports,2499,BatPro,4998,Small,February,19,Thursday
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium,Wireless Mouse,Electronics,899,TechGear,1798,Small,January,25,Sunday
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular,Smart Watch,Electronics,3299,FitTech,3299,Small,February,26,Thursday
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular,Machine Learning Basics,Books,999,AIPress,2997,Medium,March,4,Wednesday
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New,Coffee Maker,Home & Kitchen,3499,HomeBrew,17495,Large,March,29,Sunday

Final Processed Dataset

In [13]:
processed_df = final_df[[
    "Order_ID",
    "Order_Date",
    "Customer_Name",
    "City",
    "Region",
    "Membership_Type",
    "Product_Name",
    "Category",
    "Brand",
    "Quantity",
    "Unit_Price",
    "Total_Sales",
    "Payment_Method",
    "Order_Status",
    "Order_Size",
    "Month",
    "Day",
    "Day_of_Week"
]]

processed_df.head()

,Order_ID,Order_Date,Customer_Name,City,Region,Membership_Type,Product_Name,Category,Brand,Quantity,Unit_Price,Total_Sales,Payment_Method,Order_Status,Order_Size,Month,Day,Day_of_Week
0,O0001,2026-02-19,Harsh Vardhan,Noida,North,Premium,Cricket Bat,Sports,BatPro,2,2499,4998,Credit Card,Delivered,Small,February,19,Thursday
1,O0002,2026-01-25,Ishita Gupta,Bengaluru,South,Premium,Wireless Mouse,Electronics,TechGear,2,899,1798,Debit Card,Delivered,Small,January,25,Sunday
2,O0003,2026-02-26,Karan Joshi,Chandigarh,North,Regular,Smart Watch,Electronics,FitTech,1,3299,3299,Cash on Delivery,Delivered,Small,February,26,Thursday
3,O0004,2026-03-04,Maryam Khan,Hyderabad,South,Regular,Machine Learning Basics,Books,AIPress,3,999,2997,Net Banking,Delivered,Medium,March,4,Wednesday
4,O0005,2026-03-29,Reyansh Jain,Kolkata,East,New,Coffee Maker,Home & Kitchen,HomeBrew,5,3499,17495,Credit Card,Delivered,Large,March,29,Sunday

Export CSV

In [14]:
processed_df.to_csv(
    "Processed_Ecommerce_Dataset.csv",
    index=False
)

print("Processed dataset exported successfully!")

Processed dataset exported successfully!

# Observations

- The Orders, Customers, and Products datasets were successfully combined using `merge()`.
- `concat()` was demonstrated by combining two DataFrames.
- A new column, **Total_Sales**, was created using the `apply()` function.
- Order dates were converted into DateTime format, and Month, Day, and Day of the Week were extracted.
- The processed dataset combines customer, product, and order information into a single structured DataFrame suitable for further analysis.

# Conclusion

This notebook demonstrates the complete preprocessing workflow using Pandas. Multiple datasets were merged, DataFrames were concatenated, new columns were created using `apply()`, DateTime features were extracted, and the final processed dataset was exported as a CSV file. The processed dataset is clean, well-structured, and ready for further analysis or visualization.